allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
  - '@vitest/browser-playwright@5.0.2'
  - '@vitest/browser@5.0.2'
  - '@vitest/coverage-v8@5.0.2'
  - '@vitest/pretty-format@5.0.2'
  - '@vitest/ui@5.0.2'
  - '@vitest/utils@5.0.2'
  - data-urls@8.0.0
  - jsdom@30.1.2
  - tr46@7.0.0
  - whatwg-url@17.2.0
